plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.example.anhvt86_3'
    compileSdk 34

    defaultConfig {
        applicationId "com.example.anhvt86_3"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    buildFeatures{
        dataBinding true
        viewBinding true
    }
}

dependencies {

    implementation libs.appcompat
    implementation libs.material
    implementation libs.activity
    implementation libs.constraintlayout
    implementation libs.navigation.fragment
    implementation libs.navigation.ui
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core

    // Room Database
    implementation "androidx.room:room-common:2.6.1"
    implementation "androidx.room:room-runtime:2.6.1"
    annotationProcessor "androidx.room:room-compiler:2.6.1"

    // Preference
    implementation "androidx.preference:preference:1.2.1"

    // Paging
    implementation "androidx.paging:paging-rxjava2:3.3.4"
    implementation "androidx.paging:paging-runtime:3.3.4"
    implementation "androidx.paging:paging-common:3.3.4"

    // Retrofit
    implementation 'com.squareup.retrofit2:retrofit:2.9.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.9.0'
    implementation "com.squareup.retrofit2:adapter-rxjava2:2.9.0"

    // Picasso
    implementation 'com.squareup.picasso:picasso:2.71828'

    // RxJava for reactive programming
    implementation 'io.reactivex.rxjava2:rxjava:2.2.21'
    implementation 'io.reactivex.rxjava2:rxandroid:2.1.1'

    // Work Manager
    implementation "androidx.work:work-runtime:2.9.0"

    // Dagger
    implementation "com.google.dagger:dagger:2.52"
    annotationProcessor "com.google.dagger:dagger-compiler:2.51.1"

    implementation ("com.squareup.okhttp3:okhttp:4.9.1")
    implementation ("com.squareup.okhttp3:logging-interceptor:4.9.1")
}